### ISSUE TITLE
Can't load path in wasm

### ISSUE THREAD

**Issue by victoryang00** [jhasse/jngl#74]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/40686366/158179962-d79e075f-52f3-481c-982e-c51b1d6236ef.png">

You can read the code at https://victoryang00.cn/EatKano/.
I compile the project using 
```cmake
set(CMAKE_EXECUTABLE_SUFFIX ".html")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -O3 -s WASMFS=1 -s WASM=1 -s NO_EXIT_RUNTIME=1 -s ASSERTIONS=2 -s TOTAL_MEMORY=67108864 -s DEMANGLE_SUPPORT=1 -s FULL_ES2=1 -s USE_WEBGL2=1 -s NO_DISABLE_EXCEPTION_CATCHING=1 -s EXPORTED_RUNTIME_METHODS=printErr,ccall,cwrap  -s USE_ZLIB=1 -s USE_LIBPNG=1 -s USE_VORBIS=1 -s USE_FREETYPE=1 -s USE_BOOST_HEADERS=1 -s USE_LIBJPEG=1 -s MAX_WEBGL_VERSION=1 -s MIN_WEBGL_VERSION=2 -s USE_GIFLIB=2 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='[\"bmp\", \"png\", \"jpg\"]' -s USE_SDL_TTF=2 -s USE_SDL_GFX=2 -s USE_SDL_TTF=2")
```

The error throw at [No suitable image file](https://github.com/jhasse/jngl/blob/de7dd3eca274e2ccc21260940642213dd37ed6c2/src/jngl/sprite.cpp#L139), with wasmfs access error.

**Comment by jhasse** [comment]
Hi :)

The exception should contain a message with more info which is constructed here:
https://github.com/jhasse/jngl/blob/de7dd3eca274e2ccc21260940642213dd37ed6c2/src/jngl/sprite.cpp#L131-L132

Can you read the message somewhere? Most likely you're using an unsupported image format (if I remember correctly only WebP works with WASM because I had trouble compiling libpng and libjpeg with emscripten).

I wasn't able to read it just from your link (is it a Release build?).

**Comment by pinguin999** [comment]
Hi 

I think I found your problem. You have to add --preload-file image to your CMakeFile and copy the folder into your build folder (I know that's bad) to get your assets in the web build.

Docs: https://emscripten.org/docs/porting/files/packaging_files.html

More Tipps:
1. Please remove all ".png"s from your image paths in code. JNGL will add the file extension for you.
2. Convert all your images to webp. We only support webp via emscripten.
3. Put your images and music folder in a data folder. That helps with --preload-file because you than only needs one folder there.
4. In main jngl::setFont uses your system font. Change it to jngl::setFont("image/Tiejili.ttf");
5. Here you can see an working EMscripten Config: https://gitlab.com/jhasse/ggj2021/-/blob/main/CMakeLists.txt#L11

Hope that helps you.

**Comment by victoryang00** [comment]
Thanks! I'll try today.
